name: Jest -> SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm i

      - name: Run tests
        run: npm run test
      
      
      # Add deployment commands here